# Generated by Django 3.0.6 on 2020-05-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postpage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
